// This file is autogenerated by scripts/build-registry.mjs.
// Do not edit this file directly.

export const BlocksIndex: Record<
  string,
  {
    name: string
    component: () => Promise<{ default: React.ComponentType }>
  }
> = {
  "dashboard-01": {
    name: "dashboard-01",
    component: () => import("./dashboard-01/page"),
  },
  "sidebar-07": {
    name: "sidebar-07",
    component: () => import("./sidebar-07/page"),
  },
  "sidebar-03": {
    name: "sidebar-03",
    component: () => import("./sidebar-03/page"),
  },
  "login-03": {
    name: "login-03",
    component: () => import("./login-03/page"),
  },
  "login-04": {
    name: "login-04",
    component: () => import("./login-04/page"),
  },
}
