// This file is autogenerated by scripts/build-registry.mjs.
// Do not edit this file directly.

export const ExamplesIndex: Record<
  string,
  {
    name: string
    filePath: string
    component: () => Promise<Record<string, unknown>>
  }
> = {
  "accordion-demo": {
    name: "accordion-demo",
    filePath: "examples/accordion-demo.tsx",
    component: () => import("./accordion-demo"),
  },
  "accordion-multiple-and-disabled": {
    name: "accordion-multiple-and-disabled",
    filePath: "examples/accordion-multiple-and-disabled.tsx",
    component: () => import("./accordion-multiple-and-disabled"),
  },
  "alert-demo": {
    name: "alert-demo",
    filePath: "examples/alert-demo.tsx",
    component: () => import("./alert-demo"),
  },
  "alert-destructive": {
    name: "alert-destructive",
    filePath: "examples/alert-destructive.tsx",
    component: () => import("./alert-destructive"),
  },
  "alert-dialog-demo": {
    name: "alert-dialog-demo",
    filePath: "examples/alert-dialog-demo.tsx",
    component: () => import("./alert-dialog-demo"),
  },
  "alert-dialog-destructive": {
    name: "alert-dialog-destructive",
    filePath: "examples/alert-dialog-destructive.tsx",
    component: () => import("./alert-dialog-destructive"),
  },
  "alert-dialog-small": {
    name: "alert-dialog-small",
    filePath: "examples/alert-dialog-small.tsx",
    component: () => import("./alert-dialog-small"),
  },
  "alert-title-only": {
    name: "alert-title-only",
    filePath: "examples/alert-title-only.tsx",
    component: () => import("./alert-title-only"),
  },
  "alert-with-action": {
    name: "alert-with-action",
    filePath: "examples/alert-with-action.tsx",
    component: () => import("./alert-with-action"),
  },
  "alert-without-icon": {
    name: "alert-without-icon",
    filePath: "examples/alert-without-icon.tsx",
    component: () => import("./alert-without-icon"),
  },
  "badge-after-a-title": {
    name: "badge-after-a-title",
    filePath: "examples/badge-after-a-title.tsx",
    component: () => import("./badge-after-a-title"),
  },
  "badge-as-link": {
    name: "badge-as-link",
    filePath: "examples/badge-as-link.tsx",
    component: () => import("./badge-as-link"),
  },
  "badge-demo": {
    name: "badge-demo",
    filePath: "examples/badge-demo.tsx",
    component: () => import("./badge-demo"),
  },
  "badge-status": {
    name: "badge-status",
    filePath: "examples/badge-status.tsx",
    component: () => import("./badge-status"),
  },
  "badge-with-icon": {
    name: "badge-with-icon",
    filePath: "examples/badge-with-icon.tsx",
    component: () => import("./badge-with-icon"),
  },
  "breadcrumb-collapsed": {
    name: "breadcrumb-collapsed",
    filePath: "examples/breadcrumb-collapsed.tsx",
    component: () => import("./breadcrumb-collapsed"),
  },
  "breadcrumb-demo": {
    name: "breadcrumb-demo",
    filePath: "examples/breadcrumb-demo.tsx",
    component: () => import("./breadcrumb-demo"),
  },
  "breadcrumb-dropdown": {
    name: "breadcrumb-dropdown",
    filePath: "examples/breadcrumb-dropdown.tsx",
    component: () => import("./breadcrumb-dropdown"),
  },
  "breadcrumb-link": {
    name: "breadcrumb-link",
    filePath: "examples/breadcrumb-link.tsx",
    component: () => import("./breadcrumb-link"),
  },
  "breadcrumb-separator": {
    name: "breadcrumb-separator",
    filePath: "examples/breadcrumb-separator.tsx",
    component: () => import("./breadcrumb-separator"),
  },
  "button-as-link": {
    name: "button-as-link",
    filePath: "examples/button-as-link.tsx",
    component: () => import("./button-as-link"),
  },
  "button-demo": {
    name: "button-demo",
    filePath: "examples/button-demo.tsx",
    component: () => import("./button-demo"),
  },
  "button-group-demo": {
    name: "button-group-demo",
    filePath: "examples/button-group-demo.tsx",
    component: () => import("./button-group-demo"),
  },
  "button-group-input": {
    name: "button-group-input",
    filePath: "examples/button-group-input.tsx",
    component: () => import("./button-group-input"),
  },
  "button-group-nested": {
    name: "button-group-nested",
    filePath: "examples/button-group-nested.tsx",
    component: () => import("./button-group-nested"),
  },
  "button-group-split": {
    name: "button-group-split",
    filePath: "examples/button-group-split.tsx",
    component: () => import("./button-group-split"),
  },
  "button-group-vertical": {
    name: "button-group-vertical",
    filePath: "examples/button-group-vertical.tsx",
    component: () => import("./button-group-vertical"),
  },
  "button-icon": {
    name: "button-icon",
    filePath: "examples/button-icon.tsx",
    component: () => import("./button-icon"),
  },
  "button-sizes": {
    name: "button-sizes",
    filePath: "examples/button-sizes.tsx",
    component: () => import("./button-sizes"),
  },
  "button-states": {
    name: "button-states",
    filePath: "examples/button-states.tsx",
    component: () => import("./button-states"),
  },
  "button-with-icon": {
    name: "button-with-icon",
    filePath: "examples/button-with-icon.tsx",
    component: () => import("./button-with-icon"),
  },
  "calendar-demo": {
    name: "calendar-demo",
    filePath: "examples/calendar-demo.tsx",
    component: () => import("./calendar-demo"),
  },
  "calendar-disabled-days": {
    name: "calendar-disabled-days",
    filePath: "examples/calendar-disabled-days.tsx",
    component: () => import("./calendar-disabled-days"),
  },
  "calendar-multiple-week-numbers": {
    name: "calendar-multiple-week-numbers",
    filePath: "examples/calendar-multiple-week-numbers.tsx",
    component: () => import("./calendar-multiple-week-numbers"),
  },
  "calendar-range": {
    name: "calendar-range",
    filePath: "examples/calendar-range.tsx",
    component: () => import("./calendar-range"),
  },
  "calendar-single": {
    name: "calendar-single",
    filePath: "examples/calendar-single.tsx",
    component: () => import("./calendar-single"),
  },
  "calendar-with-presets": {
    name: "calendar-with-presets",
    filePath: "examples/calendar-with-presets.tsx",
    component: () => import("./calendar-with-presets"),
  },
  "card-action-cards": {
    name: "card-action-cards",
    filePath: "examples/card-action-cards.tsx",
    component: () => import("./card-action-cards"),
  },
  "card-demo": {
    name: "card-demo",
    filePath: "examples/card-demo.tsx",
    component: () => import("./card-demo"),
  },
  "card-small": {
    name: "card-small",
    filePath: "examples/card-small.tsx",
    component: () => import("./card-small"),
  },
  "checkbox-choice-card": {
    name: "checkbox-choice-card",
    filePath: "examples/checkbox-choice-card.tsx",
    component: () => import("./checkbox-choice-card"),
  },
  "checkbox-demo": {
    name: "checkbox-demo",
    filePath: "examples/checkbox-demo.tsx",
    component: () => import("./checkbox-demo"),
  },
  "checkbox-with-description": {
    name: "checkbox-with-description",
    filePath: "examples/checkbox-with-description.tsx",
    component: () => import("./checkbox-with-description"),
  },
  "collapsible-demo": {
    name: "collapsible-demo",
    filePath: "examples/collapsible-demo.tsx",
    component: () => import("./collapsible-demo"),
  },
  "command-checked-items": {
    name: "command-checked-items",
    filePath: "examples/command-checked-items.tsx",
    component: () => import("./command-checked-items"),
  },
  "command-demo": {
    name: "command-demo",
    filePath: "examples/command-demo.tsx",
    component: () => import("./command-demo"),
  },
  "command-dialog": {
    name: "command-dialog",
    filePath: "examples/command-dialog.tsx",
    component: () => import("./command-dialog"),
  },
  "command-many-items": {
    name: "command-many-items",
    filePath: "examples/command-many-items.tsx",
    component: () => import("./command-many-items"),
  },
  "context-menu-demo": {
    name: "context-menu-demo",
    filePath: "examples/context-menu-demo.tsx",
    component: () => import("./context-menu-demo"),
  },
  "dialog-demo": {
    name: "dialog-demo",
    filePath: "examples/dialog-demo.tsx",
    component: () => import("./dialog-demo"),
  },
  "dialog-footer-close-button": {
    name: "dialog-footer-close-button",
    filePath: "examples/dialog-footer-close-button.tsx",
    component: () => import("./dialog-footer-close-button"),
  },
  "dialog-form": {
    name: "dialog-form",
    filePath: "examples/dialog-form.tsx",
    component: () => import("./dialog-form"),
  },
  "dialog-without-footer": {
    name: "dialog-without-footer",
    filePath: "examples/dialog-without-footer.tsx",
    component: () => import("./dialog-without-footer"),
  },
  "drawer-demo": {
    name: "drawer-demo",
    filePath: "examples/drawer-demo.tsx",
    component: () => import("./drawer-demo"),
  },
  "drawer-directions": {
    name: "drawer-directions",
    filePath: "examples/drawer-directions.tsx",
    component: () => import("./drawer-directions"),
  },
  "dropdown-menu-checkboxes": {
    name: "dropdown-menu-checkboxes",
    filePath: "examples/dropdown-menu-checkboxes.tsx",
    component: () => import("./dropdown-menu-checkboxes"),
  },
  "dropdown-menu-demo": {
    name: "dropdown-menu-demo",
    filePath: "examples/dropdown-menu-demo.tsx",
    component: () => import("./dropdown-menu-demo"),
  },
  "dropdown-menu-disabled": {
    name: "dropdown-menu-disabled",
    filePath: "examples/dropdown-menu-disabled.tsx",
    component: () => import("./dropdown-menu-disabled"),
  },
  "dropdown-menu-inset": {
    name: "dropdown-menu-inset",
    filePath: "examples/dropdown-menu-inset.tsx",
    component: () => import("./dropdown-menu-inset"),
  },
  "dropdown-menu-radio-group": {
    name: "dropdown-menu-radio-group",
    filePath: "examples/dropdown-menu-radio-group.tsx",
    component: () => import("./dropdown-menu-radio-group"),
  },
  "field-demo": {
    name: "field-demo",
    filePath: "examples/field-demo.tsx",
    component: () => import("./field-demo"),
  },
  "field-fieldset": {
    name: "field-fieldset",
    filePath: "examples/field-fieldset.tsx",
    component: () => import("./field-fieldset"),
  },
  "field-horizontal": {
    name: "field-horizontal",
    filePath: "examples/field-horizontal.tsx",
    component: () => import("./field-horizontal"),
  },
  "field-invalid": {
    name: "field-invalid",
    filePath: "examples/field-invalid.tsx",
    component: () => import("./field-invalid"),
  },
  "field-separator": {
    name: "field-separator",
    filePath: "examples/field-separator.tsx",
    component: () => import("./field-separator"),
  },
  "hover-card-demo": {
    name: "hover-card-demo",
    filePath: "examples/hover-card-demo.tsx",
    component: () => import("./hover-card-demo"),
  },
  "hover-card-sides": {
    name: "hover-card-sides",
    filePath: "examples/hover-card-sides.tsx",
    component: () => import("./hover-card-sides"),
  },
  "input-demo": {
    name: "input-demo",
    filePath: "examples/input-demo.tsx",
    component: () => import("./input-demo"),
  },
  "input-disabled": {
    name: "input-disabled",
    filePath: "examples/input-disabled.tsx",
    component: () => import("./input-disabled"),
  },
  "input-file": {
    name: "input-file",
    filePath: "examples/input-file.tsx",
    component: () => import("./input-file"),
  },
  "input-group-button": {
    name: "input-group-button",
    filePath: "examples/input-group-button.tsx",
    component: () => import("./input-group-button"),
  },
  "input-group-demo": {
    name: "input-group-demo",
    filePath: "examples/input-group-demo.tsx",
    component: () => import("./input-group-demo"),
  },
  "input-group-invalid": {
    name: "input-group-invalid",
    filePath: "examples/input-group-invalid.tsx",
    component: () => import("./input-group-invalid"),
  },
  "input-group-text": {
    name: "input-group-text",
    filePath: "examples/input-group-text.tsx",
    component: () => import("./input-group-text"),
  },
  "input-group-textarea": {
    name: "input-group-textarea",
    filePath: "examples/input-group-textarea.tsx",
    component: () => import("./input-group-textarea"),
  },
  "input-invalid": {
    name: "input-invalid",
    filePath: "examples/input-invalid.tsx",
    component: () => import("./input-invalid"),
  },
  "input-with-button": {
    name: "input-with-button",
    filePath: "examples/input-with-button.tsx",
    component: () => import("./input-with-button"),
  },
  "input-with-label-and-hint": {
    name: "input-with-label-and-hint",
    filePath: "examples/input-with-label-and-hint.tsx",
    component: () => import("./input-with-label-and-hint"),
  },
  "item-app-list": {
    name: "item-app-list",
    filePath: "examples/item-app-list.tsx",
    component: () => import("./item-app-list"),
  },
  "item-demo": {
    name: "item-demo",
    filePath: "examples/item-demo.tsx",
    component: () => import("./item-demo"),
  },
  "item-links": {
    name: "item-links",
    filePath: "examples/item-links.tsx",
    component: () => import("./item-links"),
  },
  "item-sizes": {
    name: "item-sizes",
    filePath: "examples/item-sizes.tsx",
    component: () => import("./item-sizes"),
  },
  "kbd-demo": {
    name: "kbd-demo",
    filePath: "examples/kbd-demo.tsx",
    component: () => import("./kbd-demo"),
  },
  "kbd-in-text-and-buttons": {
    name: "kbd-in-text-and-buttons",
    filePath: "examples/kbd-in-text-and-buttons.tsx",
    component: () => import("./kbd-in-text-and-buttons"),
  },
  "kbd-quick-actions": {
    name: "kbd-quick-actions",
    filePath: "examples/kbd-quick-actions.tsx",
    component: () => import("./kbd-quick-actions"),
  },
  "label-demo": {
    name: "label-demo",
    filePath: "examples/label-demo.tsx",
    component: () => import("./label-demo"),
  },
  "label-disabled-control": {
    name: "label-disabled-control",
    filePath: "examples/label-disabled-control.tsx",
    component: () => import("./label-disabled-control"),
  },
  "menubar-demo": {
    name: "menubar-demo",
    filePath: "examples/menubar-demo.tsx",
    component: () => import("./menubar-demo"),
  },
  "popover-align": {
    name: "popover-align",
    filePath: "examples/popover-align.tsx",
    component: () => import("./popover-align"),
  },
  "popover-demo": {
    name: "popover-demo",
    filePath: "examples/popover-demo.tsx",
    component: () => import("./popover-demo"),
  },
  "popover-disabled": {
    name: "popover-disabled",
    filePath: "examples/popover-disabled.tsx",
    component: () => import("./popover-disabled"),
  },
  "popover-sides": {
    name: "popover-sides",
    filePath: "examples/popover-sides.tsx",
    component: () => import("./popover-sides"),
  },
  "progress-demo": {
    name: "progress-demo",
    filePath: "examples/progress-demo.tsx",
    component: () => import("./progress-demo"),
  },
  "progress-empty-and-complete": {
    name: "progress-empty-and-complete",
    filePath: "examples/progress-empty-and-complete.tsx",
    component: () => import("./progress-empty-and-complete"),
  },
  "progress-with-label-and-value": {
    name: "progress-with-label-and-value",
    filePath: "examples/progress-with-label-and-value.tsx",
    component: () => import("./progress-with-label-and-value"),
  },
  "radio-group-choice-cards": {
    name: "radio-group-choice-cards",
    filePath: "examples/radio-group-choice-cards.tsx",
    component: () => import("./radio-group-choice-cards"),
  },
  "radio-group-demo": {
    name: "radio-group-demo",
    filePath: "examples/radio-group-demo.tsx",
    component: () => import("./radio-group-demo"),
  },
  "select-demo": {
    name: "select-demo",
    filePath: "examples/select-demo.tsx",
    component: () => import("./select-demo"),
  },
  "select-disabled": {
    name: "select-disabled",
    filePath: "examples/select-disabled.tsx",
    component: () => import("./select-disabled"),
  },
  "select-groups": {
    name: "select-groups",
    filePath: "examples/select-groups.tsx",
    component: () => import("./select-groups"),
  },
  "select-invalid": {
    name: "select-invalid",
    filePath: "examples/select-invalid.tsx",
    component: () => import("./select-invalid"),
  },
  "select-scrollable": {
    name: "select-scrollable",
    filePath: "examples/select-scrollable.tsx",
    component: () => import("./select-scrollable"),
  },
  "select-sizes": {
    name: "select-sizes",
    filePath: "examples/select-sizes.tsx",
    component: () => import("./select-sizes"),
  },
  "separator-demo": {
    name: "separator-demo",
    filePath: "examples/separator-demo.tsx",
    component: () => import("./separator-demo"),
  },
  "separator-vertical-in-a-toolbar": {
    name: "separator-vertical-in-a-toolbar",
    filePath: "examples/separator-vertical-in-a-toolbar.tsx",
    component: () => import("./separator-vertical-in-a-toolbar"),
  },
  "sheet-demo": {
    name: "sheet-demo",
    filePath: "examples/sheet-demo.tsx",
    component: () => import("./sheet-demo"),
  },
  "sheet-sides": {
    name: "sheet-sides",
    filePath: "examples/sheet-sides.tsx",
    component: () => import("./sheet-sides"),
  },
  "sidebar-demo": {
    name: "sidebar-demo",
    filePath: "examples/sidebar-demo.tsx",
    component: () => import("./sidebar-demo"),
  },
  "sidebar-floating": {
    name: "sidebar-floating",
    filePath: "examples/sidebar-floating.tsx",
    component: () => import("./sidebar-floating"),
  },
  "sidebar-loading": {
    name: "sidebar-loading",
    filePath: "examples/sidebar-loading.tsx",
    component: () => import("./sidebar-loading"),
  },
  "skeleton-card": {
    name: "skeleton-card",
    filePath: "examples/skeleton-card.tsx",
    component: () => import("./skeleton-card"),
  },
  "skeleton-demo": {
    name: "skeleton-demo",
    filePath: "examples/skeleton-demo.tsx",
    component: () => import("./skeleton-demo"),
  },
  "skeleton-form": {
    name: "skeleton-form",
    filePath: "examples/skeleton-form.tsx",
    component: () => import("./skeleton-form"),
  },
  "slider-demo": {
    name: "slider-demo",
    filePath: "examples/slider-demo.tsx",
    component: () => import("./slider-demo"),
  },
  "slider-disabled": {
    name: "slider-disabled",
    filePath: "examples/slider-disabled.tsx",
    component: () => import("./slider-disabled"),
  },
  "slider-range-and-steps": {
    name: "slider-range-and-steps",
    filePath: "examples/slider-range-and-steps.tsx",
    component: () => import("./slider-range-and-steps"),
  },
  "slider-vertical": {
    name: "slider-vertical",
    filePath: "examples/slider-vertical.tsx",
    component: () => import("./slider-vertical"),
  },
  "switch-demo": {
    name: "switch-demo",
    filePath: "examples/switch-demo.tsx",
    component: () => import("./switch-demo"),
  },
  "switch-settings": {
    name: "switch-settings",
    filePath: "examples/switch-settings.tsx",
    component: () => import("./switch-settings"),
  },
  "table-actions": {
    name: "table-actions",
    filePath: "examples/table-actions.tsx",
    component: () => import("./table-actions"),
  },
  "table-demo": {
    name: "table-demo",
    filePath: "examples/table-demo.tsx",
    component: () => import("./table-demo"),
  },
  "table-key-value": {
    name: "table-key-value",
    filePath: "examples/table-key-value.tsx",
    component: () => import("./table-key-value"),
  },
  "table-selection": {
    name: "table-selection",
    filePath: "examples/table-selection.tsx",
    component: () => import("./table-selection"),
  },
  "tabs-demo": {
    name: "tabs-demo",
    filePath: "examples/tabs-demo.tsx",
    component: () => import("./tabs-demo"),
  },
  "tabs-icons": {
    name: "tabs-icons",
    filePath: "examples/tabs-icons.tsx",
    component: () => import("./tabs-icons"),
  },
  "tabs-line": {
    name: "tabs-line",
    filePath: "examples/tabs-line.tsx",
    component: () => import("./tabs-line"),
  },
  "tabs-vertical": {
    name: "tabs-vertical",
    filePath: "examples/tabs-vertical.tsx",
    component: () => import("./tabs-vertical"),
  },
  "textarea-demo": {
    name: "textarea-demo",
    filePath: "examples/textarea-demo.tsx",
    component: () => import("./textarea-demo"),
  },
  "textarea-disabled": {
    name: "textarea-disabled",
    filePath: "examples/textarea-disabled.tsx",
    component: () => import("./textarea-disabled"),
  },
  "textarea-invalid": {
    name: "textarea-invalid",
    filePath: "examples/textarea-invalid.tsx",
    component: () => import("./textarea-invalid"),
  },
  "textarea-with-label": {
    name: "textarea-with-label",
    filePath: "examples/textarea-with-label.tsx",
    component: () => import("./textarea-with-label"),
  },
  "toggle-demo": {
    name: "toggle-demo",
    filePath: "examples/toggle-demo.tsx",
    component: () => import("./toggle-demo"),
  },
  "toggle-disabled": {
    name: "toggle-disabled",
    filePath: "examples/toggle-disabled.tsx",
    component: () => import("./toggle-disabled"),
  },
  "toggle-group-demo": {
    name: "toggle-group-demo",
    filePath: "examples/toggle-group-demo.tsx",
    component: () => import("./toggle-group-demo"),
  },
  "toggle-group-outline": {
    name: "toggle-group-outline",
    filePath: "examples/toggle-group-outline.tsx",
    component: () => import("./toggle-group-outline"),
  },
  "toggle-group-sizes": {
    name: "toggle-group-sizes",
    filePath: "examples/toggle-group-sizes.tsx",
    component: () => import("./toggle-group-sizes"),
  },
  "toggle-group-spaced-multiple": {
    name: "toggle-group-spaced-multiple",
    filePath: "examples/toggle-group-spaced-multiple.tsx",
    component: () => import("./toggle-group-spaced-multiple"),
  },
  "toggle-group-vertical": {
    name: "toggle-group-vertical",
    filePath: "examples/toggle-group-vertical.tsx",
    component: () => import("./toggle-group-vertical"),
  },
  "toggle-outline": {
    name: "toggle-outline",
    filePath: "examples/toggle-outline.tsx",
    component: () => import("./toggle-outline"),
  },
  "toggle-sizes": {
    name: "toggle-sizes",
    filePath: "examples/toggle-sizes.tsx",
    component: () => import("./toggle-sizes"),
  },
  "tooltip-demo": {
    name: "tooltip-demo",
    filePath: "examples/tooltip-demo.tsx",
    component: () => import("./tooltip-demo"),
  },
  "tooltip-disabled": {
    name: "tooltip-disabled",
    filePath: "examples/tooltip-disabled.tsx",
    component: () => import("./tooltip-disabled"),
  },
  "tooltip-long-content": {
    name: "tooltip-long-content",
    filePath: "examples/tooltip-long-content.tsx",
    component: () => import("./tooltip-long-content"),
  },
  "tooltip-sides": {
    name: "tooltip-sides",
    filePath: "examples/tooltip-sides.tsx",
    component: () => import("./tooltip-sides"),
  },
  "tooltip-with-shortcut": {
    name: "tooltip-with-shortcut",
    filePath: "examples/tooltip-with-shortcut.tsx",
    component: () => import("./tooltip-with-shortcut"),
  },
}
