// This file is autogenerated by scripts/build-registry.mjs.
// Do not edit this file directly.

export const ExamplesIndex: Record<
  string,
  {
    name: string
    filePath: string
    component: () => Promise<Record<string, unknown>>
  }
> = {
  "accordion-demo": {
    name: "accordion-demo",
    filePath: "examples/accordion-demo.tsx",
    component: () => import("./accordion-demo"),
  },
  "accordion-multiple-and-disabled": {
    name: "accordion-multiple-and-disabled",
    filePath: "examples/accordion-multiple-and-disabled.tsx",
    component: () => import("./accordion-multiple-and-disabled"),
  },
  "alert-demo": {
    name: "alert-demo",
    filePath: "examples/alert-demo.tsx",
    component: () => import("./alert-demo"),
  },
  "alert-destructive": {
    name: "alert-destructive",
    filePath: "examples/alert-destructive.tsx",
    component: () => import("./alert-destructive"),
  },
  "alert-dialog-demo": {
    name: "alert-dialog-demo",
    filePath: "examples/alert-dialog-demo.tsx",
    component: () => import("./alert-dialog-demo"),
  },
  "alert-dialog-destructive": {
    name: "alert-dialog-destructive",
    filePath: "examples/alert-dialog-destructive.tsx",
    component: () => import("./alert-dialog-destructive"),
  },
  "alert-dialog-small": {
    name: "alert-dialog-small",
    filePath: "examples/alert-dialog-small.tsx",
    component: () => import("./alert-dialog-small"),
  },
  "alert-title-only": {
    name: "alert-title-only",
    filePath: "examples/alert-title-only.tsx",
    component: () => import("./alert-title-only"),
  },
  "alert-with-action": {
    name: "alert-with-action",
    filePath: "examples/alert-with-action.tsx",
    component: () => import("./alert-with-action"),
  },
  "alert-without-icon": {
    name: "alert-without-icon",
    filePath: "examples/alert-without-icon.tsx",
    component: () => import("./alert-without-icon"),
  },
  "aspect-ratio-demo": {
    name: "aspect-ratio-demo",
    filePath: "examples/aspect-ratio-demo.tsx",
    component: () => import("./aspect-ratio-demo"),
  },
  "aspect-ratio-portrait": {
    name: "aspect-ratio-portrait",
    filePath: "examples/aspect-ratio-portrait.tsx",
    component: () => import("./aspect-ratio-portrait"),
  },
  "aspect-ratio-square": {
    name: "aspect-ratio-square",
    filePath: "examples/aspect-ratio-square.tsx",
    component: () => import("./aspect-ratio-square"),
  },
  "attachment-demo": {
    name: "attachment-demo",
    filePath: "examples/attachment-demo.tsx",
    component: () => import("./attachment-demo"),
  },
  "attachment-group": {
    name: "attachment-group",
    filePath: "examples/attachment-group.tsx",
    component: () => import("./attachment-group"),
  },
  "attachment-image": {
    name: "attachment-image",
    filePath: "examples/attachment-image.tsx",
    component: () => import("./attachment-image"),
  },
  "attachment-sizes": {
    name: "attachment-sizes",
    filePath: "examples/attachment-sizes.tsx",
    component: () => import("./attachment-sizes"),
  },
  "attachment-states": {
    name: "attachment-states",
    filePath: "examples/attachment-states.tsx",
    component: () => import("./attachment-states"),
  },
  "attachment-trigger": {
    name: "attachment-trigger",
    filePath: "examples/attachment-trigger.tsx",
    component: () => import("./attachment-trigger"),
  },
  "avatar-badge-icon": {
    name: "avatar-badge-icon",
    filePath: "examples/avatar-badge-icon.tsx",
    component: () => import("./avatar-badge-icon"),
  },
  "avatar-badge": {
    name: "avatar-badge",
    filePath: "examples/avatar-badge.tsx",
    component: () => import("./avatar-badge"),
  },
  "avatar-basic": {
    name: "avatar-basic",
    filePath: "examples/avatar-basic.tsx",
    component: () => import("./avatar-basic"),
  },
  "avatar-demo": {
    name: "avatar-demo",
    filePath: "examples/avatar-demo.tsx",
    component: () => import("./avatar-demo"),
  },
  "avatar-dropdown": {
    name: "avatar-dropdown",
    filePath: "examples/avatar-dropdown.tsx",
    component: () => import("./avatar-dropdown"),
  },
  "avatar-group-count-icon": {
    name: "avatar-group-count-icon",
    filePath: "examples/avatar-group-count-icon.tsx",
    component: () => import("./avatar-group-count-icon"),
  },
  "avatar-group-count": {
    name: "avatar-group-count",
    filePath: "examples/avatar-group-count.tsx",
    component: () => import("./avatar-group-count"),
  },
  "avatar-group": {
    name: "avatar-group",
    filePath: "examples/avatar-group.tsx",
    component: () => import("./avatar-group"),
  },
  "avatar-size": {
    name: "avatar-size",
    filePath: "examples/avatar-size.tsx",
    component: () => import("./avatar-size"),
  },
  "badge-after-a-title": {
    name: "badge-after-a-title",
    filePath: "examples/badge-after-a-title.tsx",
    component: () => import("./badge-after-a-title"),
  },
  "badge-as-link": {
    name: "badge-as-link",
    filePath: "examples/badge-as-link.tsx",
    component: () => import("./badge-as-link"),
  },
  "badge-demo": {
    name: "badge-demo",
    filePath: "examples/badge-demo.tsx",
    component: () => import("./badge-demo"),
  },
  "badge-status": {
    name: "badge-status",
    filePath: "examples/badge-status.tsx",
    component: () => import("./badge-status"),
  },
  "badge-with-icon": {
    name: "badge-with-icon",
    filePath: "examples/badge-with-icon.tsx",
    component: () => import("./badge-with-icon"),
  },
  "breadcrumb-collapsed": {
    name: "breadcrumb-collapsed",
    filePath: "examples/breadcrumb-collapsed.tsx",
    component: () => import("./breadcrumb-collapsed"),
  },
  "breadcrumb-demo": {
    name: "breadcrumb-demo",
    filePath: "examples/breadcrumb-demo.tsx",
    component: () => import("./breadcrumb-demo"),
  },
  "breadcrumb-dropdown": {
    name: "breadcrumb-dropdown",
    filePath: "examples/breadcrumb-dropdown.tsx",
    component: () => import("./breadcrumb-dropdown"),
  },
  "breadcrumb-link": {
    name: "breadcrumb-link",
    filePath: "examples/breadcrumb-link.tsx",
    component: () => import("./breadcrumb-link"),
  },
  "breadcrumb-separator": {
    name: "breadcrumb-separator",
    filePath: "examples/breadcrumb-separator.tsx",
    component: () => import("./breadcrumb-separator"),
  },
  "bubble-alignment": {
    name: "bubble-alignment",
    filePath: "examples/bubble-alignment.tsx",
    component: () => import("./bubble-alignment"),
  },
  "bubble-collapsible": {
    name: "bubble-collapsible",
    filePath: "examples/bubble-collapsible.tsx",
    component: () => import("./bubble-collapsible"),
  },
  "bubble-demo": {
    name: "bubble-demo",
    filePath: "examples/bubble-demo.tsx",
    component: () => import("./bubble-demo"),
  },
  "bubble-group-demo": {
    name: "bubble-group-demo",
    filePath: "examples/bubble-group-demo.tsx",
    component: () => import("./bubble-group-demo"),
  },
  "bubble-link-button": {
    name: "bubble-link-button",
    filePath: "examples/bubble-link-button.tsx",
    component: () => import("./bubble-link-button"),
  },
  "bubble-popover": {
    name: "bubble-popover",
    filePath: "examples/bubble-popover.tsx",
    component: () => import("./bubble-popover"),
  },
  "bubble-reactions": {
    name: "bubble-reactions",
    filePath: "examples/bubble-reactions.tsx",
    component: () => import("./bubble-reactions"),
  },
  "bubble-tooltip": {
    name: "bubble-tooltip",
    filePath: "examples/bubble-tooltip.tsx",
    component: () => import("./bubble-tooltip"),
  },
  "bubble-variants": {
    name: "bubble-variants",
    filePath: "examples/bubble-variants.tsx",
    component: () => import("./bubble-variants"),
  },
  "button-as-link": {
    name: "button-as-link",
    filePath: "examples/button-as-link.tsx",
    component: () => import("./button-as-link"),
  },
  "button-demo": {
    name: "button-demo",
    filePath: "examples/button-demo.tsx",
    component: () => import("./button-demo"),
  },
  "button-group-demo": {
    name: "button-group-demo",
    filePath: "examples/button-group-demo.tsx",
    component: () => import("./button-group-demo"),
  },
  "button-group-input": {
    name: "button-group-input",
    filePath: "examples/button-group-input.tsx",
    component: () => import("./button-group-input"),
  },
  "button-group-nested": {
    name: "button-group-nested",
    filePath: "examples/button-group-nested.tsx",
    component: () => import("./button-group-nested"),
  },
  "button-group-split": {
    name: "button-group-split",
    filePath: "examples/button-group-split.tsx",
    component: () => import("./button-group-split"),
  },
  "button-group-vertical": {
    name: "button-group-vertical",
    filePath: "examples/button-group-vertical.tsx",
    component: () => import("./button-group-vertical"),
  },
  "button-icon": {
    name: "button-icon",
    filePath: "examples/button-icon.tsx",
    component: () => import("./button-icon"),
  },
  "button-sizes": {
    name: "button-sizes",
    filePath: "examples/button-sizes.tsx",
    component: () => import("./button-sizes"),
  },
  "button-states": {
    name: "button-states",
    filePath: "examples/button-states.tsx",
    component: () => import("./button-states"),
  },
  "button-with-icon": {
    name: "button-with-icon",
    filePath: "examples/button-with-icon.tsx",
    component: () => import("./button-with-icon"),
  },
  "calendar-demo": {
    name: "calendar-demo",
    filePath: "examples/calendar-demo.tsx",
    component: () => import("./calendar-demo"),
  },
  "calendar-disabled-days": {
    name: "calendar-disabled-days",
    filePath: "examples/calendar-disabled-days.tsx",
    component: () => import("./calendar-disabled-days"),
  },
  "calendar-multiple-week-numbers": {
    name: "calendar-multiple-week-numbers",
    filePath: "examples/calendar-multiple-week-numbers.tsx",
    component: () => import("./calendar-multiple-week-numbers"),
  },
  "calendar-range": {
    name: "calendar-range",
    filePath: "examples/calendar-range.tsx",
    component: () => import("./calendar-range"),
  },
  "calendar-single": {
    name: "calendar-single",
    filePath: "examples/calendar-single.tsx",
    component: () => import("./calendar-single"),
  },
  "calendar-with-presets": {
    name: "calendar-with-presets",
    filePath: "examples/calendar-with-presets.tsx",
    component: () => import("./calendar-with-presets"),
  },
  "card-action-cards": {
    name: "card-action-cards",
    filePath: "examples/card-action-cards.tsx",
    component: () => import("./card-action-cards"),
  },
  "card-demo": {
    name: "card-demo",
    filePath: "examples/card-demo.tsx",
    component: () => import("./card-demo"),
  },
  "card-small": {
    name: "card-small",
    filePath: "examples/card-small.tsx",
    component: () => import("./card-small"),
  },
  "carousel-api": {
    name: "carousel-api",
    filePath: "examples/carousel-api.tsx",
    component: () => import("./carousel-api"),
  },
  "carousel-demo": {
    name: "carousel-demo",
    filePath: "examples/carousel-demo.tsx",
    component: () => import("./carousel-demo"),
  },
  "carousel-orientation": {
    name: "carousel-orientation",
    filePath: "examples/carousel-orientation.tsx",
    component: () => import("./carousel-orientation"),
  },
  "carousel-size": {
    name: "carousel-size",
    filePath: "examples/carousel-size.tsx",
    component: () => import("./carousel-size"),
  },
  "carousel-spacing": {
    name: "carousel-spacing",
    filePath: "examples/carousel-spacing.tsx",
    component: () => import("./carousel-spacing"),
  },
  "chart-area": {
    name: "chart-area",
    filePath: "examples/chart-area.tsx",
    component: () => import("./chart-area"),
  },
  "chart-demo": {
    name: "chart-demo",
    filePath: "examples/chart-demo.tsx",
    component: () => import("./chart-demo"),
  },
  "chart-example-axis": {
    name: "chart-example-axis",
    filePath: "examples/chart-example-axis.tsx",
    component: () => import("./chart-example-axis"),
  },
  "chart-example-grid": {
    name: "chart-example-grid",
    filePath: "examples/chart-example-grid.tsx",
    component: () => import("./chart-example-grid"),
  },
  "chart-example-legend": {
    name: "chart-example-legend",
    filePath: "examples/chart-example-legend.tsx",
    component: () => import("./chart-example-legend"),
  },
  "chart-example-tooltip": {
    name: "chart-example-tooltip",
    filePath: "examples/chart-example-tooltip.tsx",
    component: () => import("./chart-example-tooltip"),
  },
  "chart-example": {
    name: "chart-example",
    filePath: "examples/chart-example.tsx",
    component: () => import("./chart-example"),
  },
  "chart-line": {
    name: "chart-line",
    filePath: "examples/chart-line.tsx",
    component: () => import("./chart-line"),
  },
  "chart-pie": {
    name: "chart-pie",
    filePath: "examples/chart-pie.tsx",
    component: () => import("./chart-pie"),
  },
  "chart-tooltip": {
    name: "chart-tooltip",
    filePath: "examples/chart-tooltip.tsx",
    component: () => import("./chart-tooltip"),
  },
  "checkbox-choice-card": {
    name: "checkbox-choice-card",
    filePath: "examples/checkbox-choice-card.tsx",
    component: () => import("./checkbox-choice-card"),
  },
  "checkbox-demo": {
    name: "checkbox-demo",
    filePath: "examples/checkbox-demo.tsx",
    component: () => import("./checkbox-demo"),
  },
  "checkbox-with-description": {
    name: "checkbox-with-description",
    filePath: "examples/checkbox-with-description.tsx",
    component: () => import("./checkbox-with-description"),
  },
  "collapsible-demo": {
    name: "collapsible-demo",
    filePath: "examples/collapsible-demo.tsx",
    component: () => import("./collapsible-demo"),
  },
  "combobox-auto-highlight": {
    name: "combobox-auto-highlight",
    filePath: "examples/combobox-auto-highlight.tsx",
    component: () => import("./combobox-auto-highlight"),
  },
  "combobox-basic": {
    name: "combobox-basic",
    filePath: "examples/combobox-basic.tsx",
    component: () => import("./combobox-basic"),
  },
  "combobox-clear": {
    name: "combobox-clear",
    filePath: "examples/combobox-clear.tsx",
    component: () => import("./combobox-clear"),
  },
  "combobox-custom": {
    name: "combobox-custom",
    filePath: "examples/combobox-custom.tsx",
    component: () => import("./combobox-custom"),
  },
  "combobox-demo": {
    name: "combobox-demo",
    filePath: "examples/combobox-demo.tsx",
    component: () => import("./combobox-demo"),
  },
  "combobox-disabled-items": {
    name: "combobox-disabled-items",
    filePath: "examples/combobox-disabled-items.tsx",
    component: () => import("./combobox-disabled-items"),
  },
  "combobox-disabled": {
    name: "combobox-disabled",
    filePath: "examples/combobox-disabled.tsx",
    component: () => import("./combobox-disabled"),
  },
  "combobox-groups": {
    name: "combobox-groups",
    filePath: "examples/combobox-groups.tsx",
    component: () => import("./combobox-groups"),
  },
  "combobox-input-group": {
    name: "combobox-input-group",
    filePath: "examples/combobox-input-group.tsx",
    component: () => import("./combobox-input-group"),
  },
  "combobox-invalid": {
    name: "combobox-invalid",
    filePath: "examples/combobox-invalid.tsx",
    component: () => import("./combobox-invalid"),
  },
  "combobox-multiple-disabled": {
    name: "combobox-multiple-disabled",
    filePath: "examples/combobox-multiple-disabled.tsx",
    component: () => import("./combobox-multiple-disabled"),
  },
  "combobox-multiple-invalid": {
    name: "combobox-multiple-invalid",
    filePath: "examples/combobox-multiple-invalid.tsx",
    component: () => import("./combobox-multiple-invalid"),
  },
  "combobox-multiple-no-remove": {
    name: "combobox-multiple-no-remove",
    filePath: "examples/combobox-multiple-no-remove.tsx",
    component: () => import("./combobox-multiple-no-remove"),
  },
  "combobox-multiple": {
    name: "combobox-multiple",
    filePath: "examples/combobox-multiple.tsx",
    component: () => import("./combobox-multiple"),
  },
  "combobox-popup": {
    name: "combobox-popup",
    filePath: "examples/combobox-popup.tsx",
    component: () => import("./combobox-popup"),
  },
  "command-checked-items": {
    name: "command-checked-items",
    filePath: "examples/command-checked-items.tsx",
    component: () => import("./command-checked-items"),
  },
  "command-demo": {
    name: "command-demo",
    filePath: "examples/command-demo.tsx",
    component: () => import("./command-demo"),
  },
  "command-dialog": {
    name: "command-dialog",
    filePath: "examples/command-dialog.tsx",
    component: () => import("./command-dialog"),
  },
  "command-many-items": {
    name: "command-many-items",
    filePath: "examples/command-many-items.tsx",
    component: () => import("./command-many-items"),
  },
  "context-menu-demo": {
    name: "context-menu-demo",
    filePath: "examples/context-menu-demo.tsx",
    component: () => import("./context-menu-demo"),
  },
  "data-table-demo": {
    name: "data-table-demo",
    filePath: "examples/data-table-demo.tsx",
    component: () => import("./data-table-demo"),
  },
  "data-table-reusable": {
    name: "data-table-reusable",
    filePath: "examples/data-table-reusable.tsx",
    component: () => import("./data-table-reusable"),
  },
  "dialog-demo": {
    name: "dialog-demo",
    filePath: "examples/dialog-demo.tsx",
    component: () => import("./dialog-demo"),
  },
  "dialog-footer-close-button": {
    name: "dialog-footer-close-button",
    filePath: "examples/dialog-footer-close-button.tsx",
    component: () => import("./dialog-footer-close-button"),
  },
  "dialog-form": {
    name: "dialog-form",
    filePath: "examples/dialog-form.tsx",
    component: () => import("./dialog-form"),
  },
  "dialog-without-footer": {
    name: "dialog-without-footer",
    filePath: "examples/dialog-without-footer.tsx",
    component: () => import("./dialog-without-footer"),
  },
  "direction-demo": {
    name: "direction-demo",
    filePath: "examples/direction-demo.tsx",
    component: () => import("./direction-demo"),
  },
  "drawer-demo": {
    name: "drawer-demo",
    filePath: "examples/drawer-demo.tsx",
    component: () => import("./drawer-demo"),
  },
  "drawer-directions": {
    name: "drawer-directions",
    filePath: "examples/drawer-directions.tsx",
    component: () => import("./drawer-directions"),
  },
  "dropdown-menu-checkboxes": {
    name: "dropdown-menu-checkboxes",
    filePath: "examples/dropdown-menu-checkboxes.tsx",
    component: () => import("./dropdown-menu-checkboxes"),
  },
  "dropdown-menu-demo": {
    name: "dropdown-menu-demo",
    filePath: "examples/dropdown-menu-demo.tsx",
    component: () => import("./dropdown-menu-demo"),
  },
  "dropdown-menu-disabled": {
    name: "dropdown-menu-disabled",
    filePath: "examples/dropdown-menu-disabled.tsx",
    component: () => import("./dropdown-menu-disabled"),
  },
  "dropdown-menu-inset": {
    name: "dropdown-menu-inset",
    filePath: "examples/dropdown-menu-inset.tsx",
    component: () => import("./dropdown-menu-inset"),
  },
  "dropdown-menu-radio-group": {
    name: "dropdown-menu-radio-group",
    filePath: "examples/dropdown-menu-radio-group.tsx",
    component: () => import("./dropdown-menu-radio-group"),
  },
  "empty-background": {
    name: "empty-background",
    filePath: "examples/empty-background.tsx",
    component: () => import("./empty-background"),
  },
  "empty-demo": {
    name: "empty-demo",
    filePath: "examples/empty-demo.tsx",
    component: () => import("./empty-demo"),
  },
  "empty-input-group": {
    name: "empty-input-group",
    filePath: "examples/empty-input-group.tsx",
    component: () => import("./empty-input-group"),
  },
  "empty-outline": {
    name: "empty-outline",
    filePath: "examples/empty-outline.tsx",
    component: () => import("./empty-outline"),
  },
  "field-demo": {
    name: "field-demo",
    filePath: "examples/field-demo.tsx",
    component: () => import("./field-demo"),
  },
  "field-fieldset": {
    name: "field-fieldset",
    filePath: "examples/field-fieldset.tsx",
    component: () => import("./field-fieldset"),
  },
  "field-horizontal": {
    name: "field-horizontal",
    filePath: "examples/field-horizontal.tsx",
    component: () => import("./field-horizontal"),
  },
  "field-invalid": {
    name: "field-invalid",
    filePath: "examples/field-invalid.tsx",
    component: () => import("./field-invalid"),
  },
  "field-separator": {
    name: "field-separator",
    filePath: "examples/field-separator.tsx",
    component: () => import("./field-separator"),
  },
  "form-controls": {
    name: "form-controls",
    filePath: "examples/form-controls.tsx",
    component: () => import("./form-controls"),
  },
  "form-demo": {
    name: "form-demo",
    filePath: "examples/form-demo.tsx",
    component: () => import("./form-demo"),
  },
  "hover-card-demo": {
    name: "hover-card-demo",
    filePath: "examples/hover-card-demo.tsx",
    component: () => import("./hover-card-demo"),
  },
  "hover-card-sides": {
    name: "hover-card-sides",
    filePath: "examples/hover-card-sides.tsx",
    component: () => import("./hover-card-sides"),
  },
  "input-demo": {
    name: "input-demo",
    filePath: "examples/input-demo.tsx",
    component: () => import("./input-demo"),
  },
  "input-disabled": {
    name: "input-disabled",
    filePath: "examples/input-disabled.tsx",
    component: () => import("./input-disabled"),
  },
  "input-file": {
    name: "input-file",
    filePath: "examples/input-file.tsx",
    component: () => import("./input-file"),
  },
  "input-group-button": {
    name: "input-group-button",
    filePath: "examples/input-group-button.tsx",
    component: () => import("./input-group-button"),
  },
  "input-group-demo": {
    name: "input-group-demo",
    filePath: "examples/input-group-demo.tsx",
    component: () => import("./input-group-demo"),
  },
  "input-group-invalid": {
    name: "input-group-invalid",
    filePath: "examples/input-group-invalid.tsx",
    component: () => import("./input-group-invalid"),
  },
  "input-group-text": {
    name: "input-group-text",
    filePath: "examples/input-group-text.tsx",
    component: () => import("./input-group-text"),
  },
  "input-group-textarea": {
    name: "input-group-textarea",
    filePath: "examples/input-group-textarea.tsx",
    component: () => import("./input-group-textarea"),
  },
  "input-invalid": {
    name: "input-invalid",
    filePath: "examples/input-invalid.tsx",
    component: () => import("./input-invalid"),
  },
  "input-otp-controlled": {
    name: "input-otp-controlled",
    filePath: "examples/input-otp-controlled.tsx",
    component: () => import("./input-otp-controlled"),
  },
  "input-otp-demo": {
    name: "input-otp-demo",
    filePath: "examples/input-otp-demo.tsx",
    component: () => import("./input-otp-demo"),
  },
  "input-otp-disabled": {
    name: "input-otp-disabled",
    filePath: "examples/input-otp-disabled.tsx",
    component: () => import("./input-otp-disabled"),
  },
  "input-otp-form": {
    name: "input-otp-form",
    filePath: "examples/input-otp-form.tsx",
    component: () => import("./input-otp-form"),
  },
  "input-otp-four-digits": {
    name: "input-otp-four-digits",
    filePath: "examples/input-otp-four-digits.tsx",
    component: () => import("./input-otp-four-digits"),
  },
  "input-otp-invalid": {
    name: "input-otp-invalid",
    filePath: "examples/input-otp-invalid.tsx",
    component: () => import("./input-otp-invalid"),
  },
  "input-otp-pattern": {
    name: "input-otp-pattern",
    filePath: "examples/input-otp-pattern.tsx",
    component: () => import("./input-otp-pattern"),
  },
  "input-otp-separator": {
    name: "input-otp-separator",
    filePath: "examples/input-otp-separator.tsx",
    component: () => import("./input-otp-separator"),
  },
  "input-with-button": {
    name: "input-with-button",
    filePath: "examples/input-with-button.tsx",
    component: () => import("./input-with-button"),
  },
  "input-with-label-and-hint": {
    name: "input-with-label-and-hint",
    filePath: "examples/input-with-label-and-hint.tsx",
    component: () => import("./input-with-label-and-hint"),
  },
  "item-app-list": {
    name: "item-app-list",
    filePath: "examples/item-app-list.tsx",
    component: () => import("./item-app-list"),
  },
  "item-demo": {
    name: "item-demo",
    filePath: "examples/item-demo.tsx",
    component: () => import("./item-demo"),
  },
  "item-links": {
    name: "item-links",
    filePath: "examples/item-links.tsx",
    component: () => import("./item-links"),
  },
  "item-sizes": {
    name: "item-sizes",
    filePath: "examples/item-sizes.tsx",
    component: () => import("./item-sizes"),
  },
  "kbd-demo": {
    name: "kbd-demo",
    filePath: "examples/kbd-demo.tsx",
    component: () => import("./kbd-demo"),
  },
  "kbd-in-text-and-buttons": {
    name: "kbd-in-text-and-buttons",
    filePath: "examples/kbd-in-text-and-buttons.tsx",
    component: () => import("./kbd-in-text-and-buttons"),
  },
  "kbd-quick-actions": {
    name: "kbd-quick-actions",
    filePath: "examples/kbd-quick-actions.tsx",
    component: () => import("./kbd-quick-actions"),
  },
  "label-demo": {
    name: "label-demo",
    filePath: "examples/label-demo.tsx",
    component: () => import("./label-demo"),
  },
  "label-disabled-control": {
    name: "label-disabled-control",
    filePath: "examples/label-disabled-control.tsx",
    component: () => import("./label-disabled-control"),
  },
  "marker-border": {
    name: "marker-border",
    filePath: "examples/marker-border.tsx",
    component: () => import("./marker-border"),
  },
  "marker-demo": {
    name: "marker-demo",
    filePath: "examples/marker-demo.tsx",
    component: () => import("./marker-demo"),
  },
  "marker-icon": {
    name: "marker-icon",
    filePath: "examples/marker-icon.tsx",
    component: () => import("./marker-icon"),
  },
  "marker-link-button": {
    name: "marker-link-button",
    filePath: "examples/marker-link-button.tsx",
    component: () => import("./marker-link-button"),
  },
  "marker-separator": {
    name: "marker-separator",
    filePath: "examples/marker-separator.tsx",
    component: () => import("./marker-separator"),
  },
  "marker-shimmer": {
    name: "marker-shimmer",
    filePath: "examples/marker-shimmer.tsx",
    component: () => import("./marker-shimmer"),
  },
  "marker-status": {
    name: "marker-status",
    filePath: "examples/marker-status.tsx",
    component: () => import("./marker-status"),
  },
  "marker-variants": {
    name: "marker-variants",
    filePath: "examples/marker-variants.tsx",
    component: () => import("./marker-variants"),
  },
  "menubar-demo": {
    name: "menubar-demo",
    filePath: "examples/menubar-demo.tsx",
    component: () => import("./menubar-demo"),
  },
  "message-actions": {
    name: "message-actions",
    filePath: "examples/message-actions.tsx",
    component: () => import("./message-actions"),
  },
  "message-attachment": {
    name: "message-attachment",
    filePath: "examples/message-attachment.tsx",
    component: () => import("./message-attachment"),
  },
  "message-avatar": {
    name: "message-avatar",
    filePath: "examples/message-avatar.tsx",
    component: () => import("./message-avatar"),
  },
  "message-demo": {
    name: "message-demo",
    filePath: "examples/message-demo.tsx",
    component: () => import("./message-demo"),
  },
  "message-group": {
    name: "message-group",
    filePath: "examples/message-group.tsx",
    component: () => import("./message-group"),
  },
  "message-header-footer": {
    name: "message-header-footer",
    filePath: "examples/message-header-footer.tsx",
    component: () => import("./message-header-footer"),
  },
  "message-scroller-commands": {
    name: "message-scroller-commands",
    filePath: "examples/message-scroller-commands.tsx",
    component: () => import("./message-scroller-commands"),
  },
  "message-scroller-demo": {
    name: "message-scroller-demo",
    filePath: "examples/message-scroller-demo.tsx",
    component: () => import("./message-scroller-demo"),
  },
  "message-scroller-load-history": {
    name: "message-scroller-load-history",
    filePath: "examples/message-scroller-load-history.tsx",
    component: () => import("./message-scroller-load-history"),
  },
  "message-scroller-scrollable": {
    name: "message-scroller-scrollable",
    filePath: "examples/message-scroller-scrollable.tsx",
    component: () => import("./message-scroller-scrollable"),
  },
  "native-select-demo": {
    name: "native-select-demo",
    filePath: "examples/native-select-demo.tsx",
    component: () => import("./native-select-demo"),
  },
  "native-select-disabled": {
    name: "native-select-disabled",
    filePath: "examples/native-select-disabled.tsx",
    component: () => import("./native-select-disabled"),
  },
  "native-select-groups": {
    name: "native-select-groups",
    filePath: "examples/native-select-groups.tsx",
    component: () => import("./native-select-groups"),
  },
  "native-select-invalid": {
    name: "native-select-invalid",
    filePath: "examples/native-select-invalid.tsx",
    component: () => import("./native-select-invalid"),
  },
  "native-select-sizes": {
    name: "native-select-sizes",
    filePath: "examples/native-select-sizes.tsx",
    component: () => import("./native-select-sizes"),
  },
  "navigation-menu-demo": {
    name: "navigation-menu-demo",
    filePath: "examples/navigation-menu-demo.tsx",
    component: () => import("./navigation-menu-demo"),
  },
  "navigation-menu-link-component": {
    name: "navigation-menu-link-component",
    filePath: "examples/navigation-menu-link-component.tsx",
    component: () => import("./navigation-menu-link-component"),
  },
  "pagination-demo": {
    name: "pagination-demo",
    filePath: "examples/pagination-demo.tsx",
    component: () => import("./pagination-demo"),
  },
  "pagination-disabled": {
    name: "pagination-disabled",
    filePath: "examples/pagination-disabled.tsx",
    component: () => import("./pagination-disabled"),
  },
  "pagination-icons-only": {
    name: "pagination-icons-only",
    filePath: "examples/pagination-icons-only.tsx",
    component: () => import("./pagination-icons-only"),
  },
  "popover-align": {
    name: "popover-align",
    filePath: "examples/popover-align.tsx",
    component: () => import("./popover-align"),
  },
  "popover-demo": {
    name: "popover-demo",
    filePath: "examples/popover-demo.tsx",
    component: () => import("./popover-demo"),
  },
  "popover-disabled": {
    name: "popover-disabled",
    filePath: "examples/popover-disabled.tsx",
    component: () => import("./popover-disabled"),
  },
  "popover-sides": {
    name: "popover-sides",
    filePath: "examples/popover-sides.tsx",
    component: () => import("./popover-sides"),
  },
  "progress-demo": {
    name: "progress-demo",
    filePath: "examples/progress-demo.tsx",
    component: () => import("./progress-demo"),
  },
  "progress-empty-and-complete": {
    name: "progress-empty-and-complete",
    filePath: "examples/progress-empty-and-complete.tsx",
    component: () => import("./progress-empty-and-complete"),
  },
  "progress-with-label-and-value": {
    name: "progress-with-label-and-value",
    filePath: "examples/progress-with-label-and-value.tsx",
    component: () => import("./progress-with-label-and-value"),
  },
  "questionnaire-animated": {
    name: "questionnaire-animated",
    filePath: "examples/questionnaire-animated.tsx",
    component: () => import("./questionnaire-animated"),
  },
  "questionnaire-card": {
    name: "questionnaire-card",
    filePath: "examples/questionnaire-card.tsx",
    component: () => import("./questionnaire-card"),
  },
  "questionnaire-conditional": {
    name: "questionnaire-conditional",
    filePath: "examples/questionnaire-conditional.tsx",
    component: () => import("./questionnaire-conditional"),
  },
  "questionnaire-controlled": {
    name: "questionnaire-controlled",
    filePath: "examples/questionnaire-controlled.tsx",
    component: () => import("./questionnaire-controlled"),
  },
  "questionnaire-demo": {
    name: "questionnaire-demo",
    filePath: "examples/questionnaire-demo.tsx",
    component: () => import("./questionnaire-demo"),
  },
  "questionnaire-dialog": {
    name: "questionnaire-dialog",
    filePath: "examples/questionnaire-dialog.tsx",
    component: () => import("./questionnaire-dialog"),
  },
  "questionnaire-freeform": {
    name: "questionnaire-freeform",
    filePath: "examples/questionnaire-freeform.tsx",
    component: () => import("./questionnaire-freeform"),
  },
  "questionnaire-multiple": {
    name: "questionnaire-multiple",
    filePath: "examples/questionnaire-multiple.tsx",
    component: () => import("./questionnaire-multiple"),
  },
  "questionnaire-navigation-state": {
    name: "questionnaire-navigation-state",
    filePath: "examples/questionnaire-navigation-state.tsx",
    component: () => import("./questionnaire-navigation-state"),
  },
  "questionnaire-progress": {
    name: "questionnaire-progress",
    filePath: "examples/questionnaire-progress.tsx",
    component: () => import("./questionnaire-progress"),
  },
  "questionnaire-resume": {
    name: "questionnaire-resume",
    filePath: "examples/questionnaire-resume.tsx",
    component: () => import("./questionnaire-resume"),
  },
  "questionnaire-shortcuts": {
    name: "questionnaire-shortcuts",
    filePath: "examples/questionnaire-shortcuts.tsx",
    component: () => import("./questionnaire-shortcuts"),
  },
  "questionnaire-skip": {
    name: "questionnaire-skip",
    filePath: "examples/questionnaire-skip.tsx",
    component: () => import("./questionnaire-skip"),
  },
  "questionnaire-validation": {
    name: "questionnaire-validation",
    filePath: "examples/questionnaire-validation.tsx",
    component: () => import("./questionnaire-validation"),
  },
  "radio-group-choice-cards": {
    name: "radio-group-choice-cards",
    filePath: "examples/radio-group-choice-cards.tsx",
    component: () => import("./radio-group-choice-cards"),
  },
  "radio-group-demo": {
    name: "radio-group-demo",
    filePath: "examples/radio-group-demo.tsx",
    component: () => import("./radio-group-demo"),
  },
  "resizable-demo": {
    name: "resizable-demo",
    filePath: "examples/resizable-demo.tsx",
    component: () => import("./resizable-demo"),
  },
  "resizable-handle": {
    name: "resizable-handle",
    filePath: "examples/resizable-handle.tsx",
    component: () => import("./resizable-handle"),
  },
  "resizable-vertical": {
    name: "resizable-vertical",
    filePath: "examples/resizable-vertical.tsx",
    component: () => import("./resizable-vertical"),
  },
  "scroll-area-both": {
    name: "scroll-area-both",
    filePath: "examples/scroll-area-both.tsx",
    component: () => import("./scroll-area-both"),
  },
  "scroll-area-demo": {
    name: "scroll-area-demo",
    filePath: "examples/scroll-area-demo.tsx",
    component: () => import("./scroll-area-demo"),
  },
  "scroll-area-horizontal-demo": {
    name: "scroll-area-horizontal-demo",
    filePath: "examples/scroll-area-horizontal-demo.tsx",
    component: () => import("./scroll-area-horizontal-demo"),
  },
  "select-demo": {
    name: "select-demo",
    filePath: "examples/select-demo.tsx",
    component: () => import("./select-demo"),
  },
  "select-disabled": {
    name: "select-disabled",
    filePath: "examples/select-disabled.tsx",
    component: () => import("./select-disabled"),
  },
  "select-groups": {
    name: "select-groups",
    filePath: "examples/select-groups.tsx",
    component: () => import("./select-groups"),
  },
  "select-invalid": {
    name: "select-invalid",
    filePath: "examples/select-invalid.tsx",
    component: () => import("./select-invalid"),
  },
  "select-scrollable": {
    name: "select-scrollable",
    filePath: "examples/select-scrollable.tsx",
    component: () => import("./select-scrollable"),
  },
  "select-sizes": {
    name: "select-sizes",
    filePath: "examples/select-sizes.tsx",
    component: () => import("./select-sizes"),
  },
  "separator-demo": {
    name: "separator-demo",
    filePath: "examples/separator-demo.tsx",
    component: () => import("./separator-demo"),
  },
  "separator-vertical-in-a-toolbar": {
    name: "separator-vertical-in-a-toolbar",
    filePath: "examples/separator-vertical-in-a-toolbar.tsx",
    component: () => import("./separator-vertical-in-a-toolbar"),
  },
  "sheet-demo": {
    name: "sheet-demo",
    filePath: "examples/sheet-demo.tsx",
    component: () => import("./sheet-demo"),
  },
  "sheet-sides": {
    name: "sheet-sides",
    filePath: "examples/sheet-sides.tsx",
    component: () => import("./sheet-sides"),
  },
  "sidebar-demo": {
    name: "sidebar-demo",
    filePath: "examples/sidebar-demo.tsx",
    component: () => import("./sidebar-demo"),
  },
  "sidebar-floating": {
    name: "sidebar-floating",
    filePath: "examples/sidebar-floating.tsx",
    component: () => import("./sidebar-floating"),
  },
  "sidebar-loading": {
    name: "sidebar-loading",
    filePath: "examples/sidebar-loading.tsx",
    component: () => import("./sidebar-loading"),
  },
  "skeleton-card": {
    name: "skeleton-card",
    filePath: "examples/skeleton-card.tsx",
    component: () => import("./skeleton-card"),
  },
  "skeleton-demo": {
    name: "skeleton-demo",
    filePath: "examples/skeleton-demo.tsx",
    component: () => import("./skeleton-demo"),
  },
  "skeleton-form": {
    name: "skeleton-form",
    filePath: "examples/skeleton-form.tsx",
    component: () => import("./skeleton-form"),
  },
  "slider-demo": {
    name: "slider-demo",
    filePath: "examples/slider-demo.tsx",
    component: () => import("./slider-demo"),
  },
  "slider-disabled": {
    name: "slider-disabled",
    filePath: "examples/slider-disabled.tsx",
    component: () => import("./slider-disabled"),
  },
  "slider-range-and-steps": {
    name: "slider-range-and-steps",
    filePath: "examples/slider-range-and-steps.tsx",
    component: () => import("./slider-range-and-steps"),
  },
  "slider-vertical": {
    name: "slider-vertical",
    filePath: "examples/slider-vertical.tsx",
    component: () => import("./slider-vertical"),
  },
  "sonner-actions": {
    name: "sonner-actions",
    filePath: "examples/sonner-actions.tsx",
    component: () => import("./sonner-actions"),
  },
  "sonner-demo": {
    name: "sonner-demo",
    filePath: "examples/sonner-demo.tsx",
    component: () => import("./sonner-demo"),
  },
  "sonner-description": {
    name: "sonner-description",
    filePath: "examples/sonner-description.tsx",
    component: () => import("./sonner-description"),
  },
  "sonner-position": {
    name: "sonner-position",
    filePath: "examples/sonner-position.tsx",
    component: () => import("./sonner-position"),
  },
  "sonner-types": {
    name: "sonner-types",
    filePath: "examples/sonner-types.tsx",
    component: () => import("./sonner-types"),
  },
  "spinner-badge": {
    name: "spinner-badge",
    filePath: "examples/spinner-badge.tsx",
    component: () => import("./spinner-badge"),
  },
  "spinner-button": {
    name: "spinner-button",
    filePath: "examples/spinner-button.tsx",
    component: () => import("./spinner-button"),
  },
  "spinner-color": {
    name: "spinner-color",
    filePath: "examples/spinner-color.tsx",
    component: () => import("./spinner-color"),
  },
  "spinner-demo": {
    name: "spinner-demo",
    filePath: "examples/spinner-demo.tsx",
    component: () => import("./spinner-demo"),
  },
  "spinner-input-group": {
    name: "spinner-input-group",
    filePath: "examples/spinner-input-group.tsx",
    component: () => import("./spinner-input-group"),
  },
  "spinner-sizes": {
    name: "spinner-sizes",
    filePath: "examples/spinner-sizes.tsx",
    component: () => import("./spinner-sizes"),
  },
  "switch-demo": {
    name: "switch-demo",
    filePath: "examples/switch-demo.tsx",
    component: () => import("./switch-demo"),
  },
  "switch-settings": {
    name: "switch-settings",
    filePath: "examples/switch-settings.tsx",
    component: () => import("./switch-settings"),
  },
  "table-actions": {
    name: "table-actions",
    filePath: "examples/table-actions.tsx",
    component: () => import("./table-actions"),
  },
  "table-demo": {
    name: "table-demo",
    filePath: "examples/table-demo.tsx",
    component: () => import("./table-demo"),
  },
  "table-key-value": {
    name: "table-key-value",
    filePath: "examples/table-key-value.tsx",
    component: () => import("./table-key-value"),
  },
  "table-selection": {
    name: "table-selection",
    filePath: "examples/table-selection.tsx",
    component: () => import("./table-selection"),
  },
  "tabs-demo": {
    name: "tabs-demo",
    filePath: "examples/tabs-demo.tsx",
    component: () => import("./tabs-demo"),
  },
  "tabs-icons": {
    name: "tabs-icons",
    filePath: "examples/tabs-icons.tsx",
    component: () => import("./tabs-icons"),
  },
  "tabs-line": {
    name: "tabs-line",
    filePath: "examples/tabs-line.tsx",
    component: () => import("./tabs-line"),
  },
  "tabs-vertical": {
    name: "tabs-vertical",
    filePath: "examples/tabs-vertical.tsx",
    component: () => import("./tabs-vertical"),
  },
  "textarea-demo": {
    name: "textarea-demo",
    filePath: "examples/textarea-demo.tsx",
    component: () => import("./textarea-demo"),
  },
  "textarea-disabled": {
    name: "textarea-disabled",
    filePath: "examples/textarea-disabled.tsx",
    component: () => import("./textarea-disabled"),
  },
  "textarea-invalid": {
    name: "textarea-invalid",
    filePath: "examples/textarea-invalid.tsx",
    component: () => import("./textarea-invalid"),
  },
  "textarea-with-label": {
    name: "textarea-with-label",
    filePath: "examples/textarea-with-label.tsx",
    component: () => import("./textarea-with-label"),
  },
  "toast-demo": {
    name: "toast-demo",
    filePath: "examples/toast-demo.tsx",
    component: () => import("./toast-demo"),
  },
  "toast-promise": {
    name: "toast-promise",
    filePath: "examples/toast-promise.tsx",
    component: () => import("./toast-promise"),
  },
  "toast-types": {
    name: "toast-types",
    filePath: "examples/toast-types.tsx",
    component: () => import("./toast-types"),
  },
  "toggle-demo": {
    name: "toggle-demo",
    filePath: "examples/toggle-demo.tsx",
    component: () => import("./toggle-demo"),
  },
  "toggle-disabled": {
    name: "toggle-disabled",
    filePath: "examples/toggle-disabled.tsx",
    component: () => import("./toggle-disabled"),
  },
  "toggle-group-demo": {
    name: "toggle-group-demo",
    filePath: "examples/toggle-group-demo.tsx",
    component: () => import("./toggle-group-demo"),
  },
  "toggle-group-outline": {
    name: "toggle-group-outline",
    filePath: "examples/toggle-group-outline.tsx",
    component: () => import("./toggle-group-outline"),
  },
  "toggle-group-sizes": {
    name: "toggle-group-sizes",
    filePath: "examples/toggle-group-sizes.tsx",
    component: () => import("./toggle-group-sizes"),
  },
  "toggle-group-spaced-multiple": {
    name: "toggle-group-spaced-multiple",
    filePath: "examples/toggle-group-spaced-multiple.tsx",
    component: () => import("./toggle-group-spaced-multiple"),
  },
  "toggle-group-vertical": {
    name: "toggle-group-vertical",
    filePath: "examples/toggle-group-vertical.tsx",
    component: () => import("./toggle-group-vertical"),
  },
  "toggle-outline": {
    name: "toggle-outline",
    filePath: "examples/toggle-outline.tsx",
    component: () => import("./toggle-outline"),
  },
  "toggle-sizes": {
    name: "toggle-sizes",
    filePath: "examples/toggle-sizes.tsx",
    component: () => import("./toggle-sizes"),
  },
  "tooltip-demo": {
    name: "tooltip-demo",
    filePath: "examples/tooltip-demo.tsx",
    component: () => import("./tooltip-demo"),
  },
  "tooltip-disabled": {
    name: "tooltip-disabled",
    filePath: "examples/tooltip-disabled.tsx",
    component: () => import("./tooltip-disabled"),
  },
  "tooltip-long-content": {
    name: "tooltip-long-content",
    filePath: "examples/tooltip-long-content.tsx",
    component: () => import("./tooltip-long-content"),
  },
  "tooltip-sides": {
    name: "tooltip-sides",
    filePath: "examples/tooltip-sides.tsx",
    component: () => import("./tooltip-sides"),
  },
  "tooltip-with-shortcut": {
    name: "tooltip-with-shortcut",
    filePath: "examples/tooltip-with-shortcut.tsx",
    component: () => import("./tooltip-with-shortcut"),
  },
}
